### ISSUE TITLE
Deserializing GBZ can fail when the graph has walks in multiple connected components

### ISSUE THREAD

**Issue by adamnovak** [jltsiren/gbwtgraph#17]
Take this GFA as `in.gfa`:

```
H	VN:Z:1.0
S	11	G
S	21	G
W	sample	1	A	0	1	>11
W	sample	1	B	0	1	>21
```

And do:

```
bin/gfa2gbwt -b in
bin/gfa2gbwt -C in
cp in.gbz out.gbz
bin/gfa2gbwt -D out
```

It won't wound-trip the `.gg` and `.gbwt` through GBZ; it will instead fail with:

```
terminate called after throwing an instance of 'sdsl::simple_sds::InvalidData'
  what():  Invalid number of buckets
Aborted
```

**Comment by adamnovak** [comment]
This happens if you build in a `vg` that uses `sdsl-lite` commit `ffc8ed5337aa0d01cf4f2c60e619a873e0b0ce7d`, which is the submodule referenced in `gbwt` commit `5d0b136a3bc0772d3e02e0e4b261de8d75268e7b`, which current master `gbwtgraph` references.

I tried to "upgrade" vg to the "right" `sdsl-lite` as referenced in this repo, and it turned out vg had the newer, working version already. When I use `sdsl-lite` commit `d4105e78ea42f8aeacb18a5ec8983430ef6190fb` the problem goes away.

Maybe we should drop the submodules from this repo and/or from gbwt? If they don't actually describe versions known to work together, they can cause trouble like this.

**Comment by jltsiren** [comment]
The submodules are only used in the cmake build, which was originally intended for the Debian build of VG. I'm not sure if it's necessary anymore. I try to keep the cmake build up to date, but because I don't really use it myself, it's not properly tested.

**Comment by adamnovak** [comment]
I haven't been able to get the CMake build to build for me.

**Comment by jltsiren** [comment]
It looks like the CMake builds have been broken for both GBWT and GBWTGraph since I reorganized the files in May. As nobody has noticed it until now, it seems safe to assume that nobody needs them anymore.
