### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by gsc74** [jltsiren/gbwtgraph#38]
@jltsiren , I got the following error while compiling the tool with `make`

````
src/subgraph.cpp:507:53: error: ‘const class gbwt::Metadata’ has no member named ‘full_path’; did you mean ‘fullPath’?
   gbwt::FullPathName path_name = gbz.index.metadata.full_path(path_id);
                                                     ^~~~~~~~~
                                                     fullPath
````

**Comment by jltsiren** [comment]
I'm in the middle of making some changes to GBWT and GBWTGraph in parallel, and apparently that name change got into the master branch of one but not the other. You can replace the `full_path` function with `fullPath`, and it should work. It should be fixed in the master in a few days.

**Comment by gsc74** [comment]
I'm using the source code from the release and that fixed the issue. 
Thanks!
